name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pylint Black Flake8 Isort & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black isort
    - name: Linting with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 5
    - name: Formatting isort
      run: |
        python -m isort --profile black merchex
    - name: Formatting checks isort
      run: |
        python -m isort --profile black --check merchex
    - name: Fortmatting black
      run: |
        python -m black merchex
    - name: Formatting checks black
      run: |
        python -m black --check merchex
